### ISSUE TITLE
Drop windows specific bits

### ISSUE THREAD

**Issue by mbiebl** [rsyslog/libfastjson#10]
If no-one is actively using/testing the windows specific bits, as it looks like, I think windows support is better removed, including stuff like
README-WIN32.html
config.h.win32
json-c.vcproj

(and the references to those files)

**Comment by rgerhards** [comment]
I, too, think this makes sense.

**Comment by rgerhards** [comment]
The same holds true for Android-specific stuff, as we do no target that either.

**Comment by rgerhards** [comment]
done with above patch
