### ISSUE TITLE
linkhash.c does not use atomic macros from atomic.h

### ISSUE THREAD

**Issue by ThalesCanada** [rsyslog/libfastjson#105]
0.99..2 release

linkhash.c in function lh_char_hash calls __sync_val_compare_and_swap directly instead of the ATOMIC_CAS_VAL compatibility macro defined in atomic.h. This causes link-time errors in rsyslog when cross-compiling for any architecture that lacks that sync_val_compare_and_swap function.

**Comment by rgerhards** [comment]
This function has been removed.
