### ISSUE TITLE
encode chinese error!

### ISSUE THREAD

**Issue by zhanglong2005** [rsyslog/libfastjson#106]
libfastjson can't encode chinese correct.

i change test_parse.c like this:
       new_obj = fjson_tokener_parse("// hello\n\"张龙\"");
print:
       new_obj.to_string()============================"\u00E50.0\u00E9099"

from this,you can see clearly that \u00E50.0\u00E9099 is not a correct unicode.

**Comment by rgerhards** [comment]
This is probably the same as https://github.com/rsyslog/libfastjson/issues/107
