### ISSUE TITLE
handle escaped utf-8

### ISSUE THREAD

**Issue by ldv** [rsyslog/libfastjson#107]
The library does not seem to handle UTF-8 escaped strings correctly.

```
int main(void)
{
  char *s;
  json_object *json;
  
  s = "{ \"foo\" : \"\u00a9\" }";

  printf("string = %s\n", s);
  json = json_tokener_parse(s);
  printf("json = %s\n", json_object_to_json_string_ext(json, JSON_C_TO_STRING_PRETTY));

  json_object_put(json);
}
```

Output:
```
string = { "foo" : "©" }
json = {
  "foo":"\u00

```

Maybe I'm doing something wrong, or is it a bug?

**Comment by rgerhards** [comment]
This goes back to the code that we forked from, and in their tracker there is some additional discussion: https://github.com/json-c/json-c/issues/237

**Comment by rgerhards** [comment]
I can at least reproduce the issue with current git master branch, albeit a bit different:
```
string = { "foo" : "©" }
json = {
  "foo":"\u00-2\u00.9"
}
```

**Comment by rgerhards** [comment]
This problem happens due to sign extension, as we have ```char``` data type. This is negative, so when it is used as an interger, the negative vlaue is preserved. That most probably causes the indexing operation in ```fjson_escape_str()``` to fail. The proper cure would be to change all these chars to ```unsigned char```, but that might be a lot of effort.

**Comment by rgerhards** [comment]
Note: this is NOT related to the bug filed in json-c. If there really is a bug in json-c with similar effects, it has a different root cause.

**Comment by ldv** [comment]
I tested with json-c and the bug is not present. Thank you for the fix!
