### ISSUE TITLE
libfastjson 0.99.3 is not tagged in git

### ISSUE THREAD

**Issue by andreasstieger** [rsyslog/libfastjson#114]
There is a [release announcement for libfastjson 0.99.3](http://www.rsyslog.com/libfastjson-0-99-3-released/) made by @friedl.

There is no corresponding git tag.

**Comment by rgerhards** [comment]
sorry for the confusion. This was my fault. I did not push to github (now done) when I begun to track down packaging issues we had on the rsyslog projects packages.
