### ISSUE TITLE
Please add benchmarks

### ISSUE THREAD

**Issue by rockdaboot** [rsyslog/libfastjson#153]
You make some efforts to create a library being faster and smaller then the original. I really appreciate that. But you should add some comparisons for typical uses, corner cases, file size to the README.md.

Just saying isn't enough here.

**Comment by rgerhards** [comment]
I see your point, but unfortunately I do not have time at the moment to add these benchmarks. We know from the rsyslog community very well that libfastjson is considerably faster, but I understand if you do not want to dive into it.

Some discussion on the performance can be found in this paper: https://www.researchgate.net/publication/310545144_Efficient_Normalization_of_IT_Log_Messages_under_Realtime_Conditions

Search for "libfastjson" inside the PDF. It does not give concrete pointers for json-c performance, but tells you the the profiler data was dominated by it in an extreme way where as it describes samples with libfastjson.

**Comment by rockdaboot** [comment]
Thanks for the pointer. I was there was simple reproducer, optimally within libfastjson. E.g. a 'make bench' to recreate the results.

Anyways, from what I read the results are valid for many test samples done in a close loop. While my use cases like won't see much speed improvements. Also, the size doesn't make a big difference (on Debian unstable):
```
libjson-c.so.3.0.1: 43304 bytes
libfastjson.so.4.2.0: 43720 bytes
```

While I will likely decide to go with libjson-c, I like your improvements. From a maintainers point of view it might be the best to get as much as possible from libfastjson into libjson-c. Else one of the projects might bit-rot. And that would be sad for several reasons.

**Comment by rgerhards** [comment]
> E.g. a 'make bench' to recreate the results.

ack, that would be useful

> Also, the size doesn't make a big difference (on Debian unstable):

sorry, I overlooked that - size primarily means "source code size (complexit)"

> From a maintainers point of view it might be the best to get as much as possible from libfastjson into libjson-c. 

It's hard to get them in, as the architecture has diverged quite a lot. I removed a couple of exotic features and some cleanup was done.

> Else one of the projects might bit-rot.

We use libfastjson intensively inside the rsyslog family of projects. Without it, we would not be able to provide sufficiently fast speed in JSON processing. So this work is not lost.

**Comment by rockdaboot** [comment]
> I removed a couple of exotic features and some cleanup was done.

Cleanups normally should be accepted by upstream (but I don't know how responsive the maintainers are, will have a look). So, those exotic features were the main performance killer !? Do you remember what it was ?

> ... So this work is not lost.

I didn't mean the work gets lost. I think more of improvements and bug fixes (code, docs, build system, ...). Do you track if those are made in libjson-c and check if they are relevant to libfastjson ? You mentioned, you don't have much time... so maybe not !?

**Comment by rgerhards** [comment]
> Cleanups normally should be accepted by upstream (but I don't know how responsive the maintainers are, will have a look).

my experience in this regard is not the best - it was part why we initially forked: http://blog.gerhards.net/2015/12/rsyslog-and-liblognorm-will-switch-to.html

> So, those exotic features were the main performance killer !? Do you remember what it was ?

No, it's a myriad of smaller and bigger things. Overall code and design.

For a sample of an exotic feature, see here https://github.com/rsyslog/libfastjson/pull/141

> I didn't mean the work gets lost. I think more of improvements and bug fixes (code, docs, build system, ...). Do you track if those are made in libjson-c and check if they are relevant to libfastjson ? You mentioned, you don't have much time... so maybe not !?

I initially did, but the code bases have diverged very far, so there nowadays is little benefit in doing so. The tokener is more or less the only component that's still 99% the same.
