### ISSUE TITLE
why is json_config.h needed?

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/libfastjson#41]
can this be removed?

**Comment by rgerhards** [comment]
this seems to be closely related to json_inttypes.h, which is also questionable.

**Comment by rgerhards** [comment]
it is not needed, but json_inttypes.h needs to stay for the time being. It's a cross-platform tool.

**Comment by mbiebl** [comment]
since json_inttypes.h references config.h, and json_inttypes.h is installed to /usr/include, config.h will need to be installed as well, and in this case, naming it json_config.h seems more appropriate.

**Comment by mbiebl** [comment]
So, I think this commit should be reverted, unless we stop installing json_inttypes.h to /usr/include

**Comment by mbiebl** [comment]
or json_inttypes.h is changed to not include config.h

**Comment by rgerhards** [comment]
ah, you are right. I have overlooked this. But before reverting, let's check if json_inttypes.h is really needed. I don't think so for Linux, it smells a bit like Windows-support.
