### ISSUE TITLE
make github releases (here: 0.99.1)

### ISSUE THREAD

**Issue by andreasstieger** [rsyslog/libfastjson#6]
Apparently you are distributing binary and source package of an 0.99.1 release at http://rpms.adiscon.com/v8-stable/epel-7/x86_64/RPMS/libfastjson-0.99.1-1.el7.src.rpm

Please create a corresponding tag in git, and distribute the bootstrapped tarball.

**Comment by rgerhards** [comment]
0.99.1 must be a problem with Adiscon's release team. But to fix it, I think I will issue an official 0.99.2 version soon.

**Comment by andreasstieger** [comment]
@rgerhards ah thanks. I understand the main tarball distribution point is http://download.rsyslog.com/libfastjson/ anyway.

**Comment by rgerhards** [comment]
jupp right

**Comment by rgerhards** [comment]
FYI:I do a little cleanup today and hope to be able to release either this evening or tomorrow as 0.99.2, resolving all confusion (hopefully ;))
