### ISSUE TITLE
rename fjson_c_get_random_seed to fjson_get_random_seed

### ISSUE THREAD

**Issue by mbiebl** [rsyslog/libfastjson#72]
fjson_c_get_random_seed() seem to be the only left-over from the json_c_ → fjson_ renaming.

I think we should address that straggler too

**Comment by rgerhards** [comment]
I'll probably remove this function today or tomorrow, thus I did not yet care.

Note that 1.0 may include it if the removal of hash tables does not work out. So maybe I should fix it anyhow. ;)

**Comment by rgerhards** [comment]
closing based on assumption we will not re-enable hash table code. If we do, this needs to be reopened.
